version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/templates           # Volume pour synchroniser le code source

volumes:
  templates: